#!/usr/bin/env python

import sys
import pli

if len(sys.argv) < 3:
	print 'Please specify IP and value to query.'
	print 'usage: ' + sys.argv[0] + ' 172.31.2.110 50'
	sys.exit(0)

p = pli.PLI((sys.argv[1], 26000), timeout=5, retries=5, retry_delay=3.0)

assert p.loopback_test() # check everything is A-OK

print p.get_value(int(sys.argv[2])),
